export { default as ProjectManagePage } from './projects-manage'
export { default as AssessDateManagePage } from './assess-date-manage'
export { default as AssessPage } from './assess-page'
export { default as CriteriasDetailPage } from './criterias-detail/:id'
export { default as CriteriasManagePage } from './criterias-manage'
export { default as DepartmentsManagePage } from './departments-manage'
export { default as EmployeeManagePage } from './employee-manage'
export { default as UserDetailRatingPage } from './user-detail-rating/:userId'