export { default as ProjectManagePage } from './projects-manage/index.vue'
export { default as AssessDateManagePage } from './assess-date-manage/index.vue'
export { default as AssessPage } from './assess-page/index.vue'
export { default as CriteriasDetailPage } from './criterias-detail/[id].vue'
export { default as CriteriasManagePage } from './criterias-manage/index.vue'
export { default as DepartmentsManagePage } from './departments-manage/index.vue'
export { default as EmployeeManagePage } from './employee-manage/index.vue'
export { default as UserDetailRatingPage } from './user-detail-rating/[userId].vue'